version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "deps"

  - package-ecosystem: "npm"
    directory: "/bot/dashboard_v2"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "javascript"
    commit-message:
      prefix: "deps"
    ignore:
      - dependency-name: "eslint"
        versions:
          - ">=10"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "deps"
