"""Legal pages mixin: Impressum + Datenschutz (§5 TMG / DSGVO)."""

from __future__ import annotations

from aiohttp import web


class _DashboardLegalMixin:
    """Handlers for /twitch/impressum and /twitch/datenschutz — no auth required."""

    async def abbo_impressum(self, request: web.Request) -> web.StreamResponse:  # noqa: ARG002
        """GET /twitch/impressum — §5 TMG. Must be accessible without login."""
        page = (
            "<!doctype html><html lang='de'><head><meta charset='utf-8'>"
            "<meta name='viewport' content='width=device-width,initial-scale=1'>"
            "<title>Impressum · EarlySalty</title>"
            "<style>"
            "body{margin:0;background:#f8fafc;color:#0f172a;"
            "font-family:Segoe UI,Arial,sans-serif;line-height:1.7;}"
            ".wrap{max-width:700px;margin:0 auto;padding:40px 20px 60px;}"
            "h1{font-size:1.7rem;margin:0 0 6px;font-weight:800;}"
            ".back{font-size:13px;color:#64748b;margin-bottom:24px;display:block;"
            "text-decoration:none;}"
            ".back:hover{color:#2563eb;}"
            "h2{font-size:1.05rem;margin:26px 0 6px;color:#0f172a;font-weight:700;}"
            "p,address{font-size:15px;color:#334155;font-style:normal;margin:0 0 8px;}"
            "a{color:#2563eb;text-decoration:none;}"
            "a:hover{text-decoration:underline;}"
            ".sub{color:#64748b;font-size:14px;margin:0 0 20px;}"
            ".footer{margin-top:40px;font-size:12px;color:#94a3b8;"
            "border-top:1px solid #e2e8f0;padding-top:14px;}"
            "</style></head><body><div class='wrap'>"
            "<a class='back' href='/twitch/abbo'>&larr; Zurück zu den Plänen</a>"
            "<h1>Impressum</h1>"
            "<p class='sub'>Angaben gemäß § 5 TMG</p>"
            "<h2>Betreiber</h2>"
            "<address>Nathanael Golla<br>Binger Straße 5<br>55263 Wackernheim</address>"
            "<h2>Kontakt</h2>"
            "<p><a href='mailto:mail@earlysalty.com'>mail@earlysalty.com</a></p>"
            "<h2>Verantwortlich für den Inhalt</h2>"
            "<p>Verantwortlich für den Inhalt nach § 18 Abs. 2 MStV:<br>"
            "Nathanael Golla, Anschrift wie oben.</p>"
            "<div class='footer'>"
            "<a href='/twitch/abbo'>Pläne</a>"
            " &nbsp;&middot;&nbsp; "
            "<a href='/twitch/datenschutz'>Datenschutz</a>"
            "</div>"
            "</div></body></html>"
        )
        return web.Response(text=page, content_type="text/html")

    async def abbo_datenschutz(self, request: web.Request) -> web.StreamResponse:  # noqa: ARG002
        """GET /twitch/datenschutz — DSGVO Art. 13/14. Must be accessible without login."""
        page = (
            "<!doctype html><html lang='de'><head><meta charset='utf-8'>"
            "<meta name='viewport' content='width=device-width,initial-scale=1'>"
            "<title>Datenschutz · EarlySalty</title>"
            "<style>"
            "body{margin:0;background:#f8fafc;color:#0f172a;"
            "font-family:Segoe UI,Arial,sans-serif;line-height:1.7;}"
            ".wrap{max-width:700px;margin:0 auto;padding:40px 20px 60px;}"
            "h1{font-size:1.7rem;margin:0 0 6px;font-weight:800;}"
            ".back{font-size:13px;color:#64748b;margin-bottom:24px;display:block;"
            "text-decoration:none;}"
            ".back:hover{color:#2563eb;}"
            "h2{font-size:1.05rem;margin:26px 0 6px;color:#0f172a;font-weight:700;}"
            "p{font-size:15px;color:#334155;margin:0 0 10px;}"
            "ul{font-size:15px;color:#334155;margin:0 0 10px;padding-left:22px;}"
            "li{margin-bottom:4px;}"
            "a{color:#2563eb;text-decoration:none;}"
            "a:hover{text-decoration:underline;}"
            ".sub{color:#64748b;font-size:14px;margin:0 0 20px;}"
            ".footer{margin-top:40px;font-size:12px;color:#94a3b8;"
            "border-top:1px solid #e2e8f0;padding-top:14px;}"
            "</style></head><body><div class='wrap'>"
            "<a class='back' href='/twitch/abbo'>&larr; Zurück zu den Plänen</a>"
            "<h1>Datenschutzerklärung</h1>"
            "<p class='sub'>Stand: Februar 2026</p>"
            "<h2>Verantwortlicher</h2>"
            "<p>Nathanael Golla<br>Binger Straße 5, 55263 Wackernheim<br>"
            "<a href='mailto:mail@earlysalty.com'>mail@earlysalty.com</a></p>"
            "<h2>Erhobene Daten</h2>"
            "<p>Beim Login und bei der Nutzung des Dienstes werden folgende Daten verarbeitet:</p>"
            "<ul>"
            "<li>Twitch OAuth: Twitch-Name, Twitch-ID, E-Mail-Adresse</li>"
            "<li>Zahlungsdaten: werden ausschließlich über Stripe verarbeitet (s.&nbsp;u.)</li>"
            "</ul>"
            "<h2>Stripe als Zahlungsdienstleister</h2>"
            "<p>Zahlungen werden über Stripe Payments Europe Ltd. abgewickelt. "
            "Stripe verarbeitet Zahlungsdaten als eigenverantwortlicher Verantwortlicher "
            "gemäß seiner eigenen Datenschutzrichtlinie: "
            "<a href='https://stripe.com/de/privacy' target='_blank' "
            "rel='noopener noreferrer'>stripe.com/de/privacy</a>.</p>"
            "<h2>Speicherdauer</h2>"
            "<p>Deine Daten werden gespeichert, solange dein Abonnement aktiv ist oder "
            "gesetzliche Aufbewahrungspflichten bestehen "
            "(z.&nbsp;B. steuerrechtlich 10 Jahre für Rechnungsdaten).</p>"
            "<h2>Deine Rechte (Art. 15–22 DSGVO)</h2>"
            "<ul>"
            "<li>Auskunft über gespeicherte Daten (Art. 15)</li>"
            "<li>Berichtigung unrichtiger Daten (Art. 16)</li>"
            "<li>Löschung deiner Daten (Art. 17)</li>"
            "<li>Einschränkung der Verarbeitung (Art. 18)</li>"
            "<li>Datenübertragbarkeit (Art. 20)</li>"
            "<li>Widerspruch gegen die Verarbeitung (Art. 21)</li>"
            "</ul>"
            "<p>Zur Wahrnehmung dieser Rechte wende dich an: "
            "<a href='mailto:mail@earlysalty.com'>mail@earlysalty.com</a></p>"
            "<h2>Beschwerderecht</h2>"
            "<p>Du hast das Recht, dich bei der zuständigen Datenschutz-Aufsichtsbehörde "
            "zu beschweren. Zuständig ist der <em>Landesbeauftragte für den Datenschutz "
            "und die Informationsfreiheit Rheinland-Pfalz (LfDI)</em>, "
            "Hintere Bleiche 34, 55116 Mainz.</p>"
            "<div class='footer'>"
            "<a href='/twitch/abbo'>Pläne</a>"
            " &nbsp;&middot;&nbsp; "
            "<a href='/twitch/impressum'>Impressum</a>"
            "</div>"
            "</div></body></html>"
        )
        return web.Response(text=page, content_type="text/html")
